### ISSUE TITLE
Research and acquire plant to use for testing

### ISSUE THREAD

**Issue by hellcatf6** [EECE3093C/team-project-green#21]
Research potential plants to use for our test.

**Comment by hellcatf6** [comment]
potential plant for use.
https://hirts.com/fire-pepper-plant-worlds-smallest-pepper-tasty-2-5-pot-grow-inside-out/

**Comment by hellcatf6** [comment]
The Fire Pepper is an dwarf pepper perfect for outdoor borders or indoor pots. The plant of Fire Chili grows about 6 inches high and spreading 12 inches in width. The fruit of Fire Chili is short and pointed with a length of 0.5 inch and a diameter of 0.2 inches. The Fire Chili has yellow, orange and red peppers growing through the top of the foliage. 
One tiny plant will give you a non-stop crop of mini, hot peppers
One of the smallest peppers in the world
Yellow, orange and red peppers growing through the top of the foliage, and ideal for canning, pickling or simply added to salsa
Grow inside or out in full sun
Immediate Shipping in a 2.5" pot

Quoted from the above website

**Comment by hellcatf6** [comment]
Plant seeds 1/8 inch deep and keep the soil moist but not waterlogged.

Place the seed trays or pots in a warm place or on a warming mat set at 75°F. They need temps of 75 to 80°F to germinate, which typically takes about two weeks.

Being tropical plants, chilis like a lot of light.

These plants prefer a temperature range of 55 to 65°F at night and 70 to 80°F during the day.

They like well-draining soil that’s fairly rich in organic matter. If you’re transplanting into containers, place some drainage material such as gravel in the bottom of the pot.

**Comment by hellcatf6** [comment]
It seems like these plants need almost constant sun and like it warm, which might cause issues when growing indoors. They also seem to need well-draining soil (so not clay) but it should be easy to find that kind of soil at a store.

**Comment by hellcatf6** [comment]
Looking alternatively into aloe plants:
Place your aloe in a bright, sunny place. Otherwise it will go dormant and stop growing. Water the plant heavily about once every two weeks, waiting until the soil dries out fully. Since this is a desert species, keeping the dirt moist will cause the roots to rot. Limp or brown leaves also signal you've overdone the H20.

Since we want to test our moisture sensor probably need a plant that gets water more frequently, however the fact it wants the soil fully dried out before each watering could be an clear testing mark for our sensor.

**Comment by hellcatf6** [comment]
Looking alternatively at the peace lily:
Water your peace lily regularly, ideally so the compost never completely dried out but is also not waterlogged. As a general rule, wait until the top few centimeters of compost have dried out before watering again. If you don't water them often enough you'll soon be able to tell – peace lilies wilt when dehydrated. Simply water again and keep up your watering regime. 
Grow peace lily in a bright spot out of direct sunlight.

Seems like a really good choice as the sunlight requirements are not harsh and it likes regular waterings. Added bonus since the lily starts to droop when underwatered we can better calibrate based on this sign.

**Comment by hellcatf6** [comment]
Peace Lily:
https://www.lowes.com/pd/Costa-Farms/5013595865

Likely needs to be shipped so will take a few days after purchase to arrive.

**Comment by jack-margeson** [comment]
@hellcatf6 I'll be up in Mason this weekend--so if you have a final plant in mind, let me know and I can swing by Lowes or Home Depot or something and pick it up :+1:

**Comment by jack-margeson** [comment]
Asked the worker at Lowe's if they had any peace lillies in stock--but they said that they're out of season. I asked them what they would suggest for our project requirements (low light, high water) and they suggested this berry allusion arrowhead plant which should work for our testing purposes. I attached a picture of it below, and I'll update the repo with a picture for documentation purposes to close this ticket.

![Image](https://user-images.githubusercontent.com/31900546/227805756-f8dc5da9-cc5a-44e9-92a4-8e833da1ce83.png)
